
version: 2

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0.362
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: gradle build
      - store_test_results:
          path: build/test-results/test

  publish:
    docker:
      - image: cimg/openjdk:8.0.362
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: gradle publish

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: main
            tags:
              ignore: /.*/

  build-and-publish:
    jobs:
      - build:
          filters: &filters-build-and-publish
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - publish:
          requires:
            - build
          filters:
            <<: *filters-build-and-publish
